import {
  SyncLogSchema,
  TrunkScanSnapshotSchema,
  type SyncLog,
  type TrunkScanSnapshot,
} from "~/server/orchestra/schemas";

/** Pure fixture builder for Module B paint tests / UI (no git). */
export function fixtureTrunkScan(
  overrides?: Partial<TrunkScanSnapshot>,
): TrunkScanSnapshot {
  const now = new Date().toISOString();
  const base: TrunkScanSnapshot = {
    schema: "orchestra.trunk_scan.v1",
    repoId: "11111111-1111-4111-8111-111111111111",
    repoSlug: "fixture-repo",
    displayName: "Fixture Repo",
    baseBranch: "main",
    scannedAt: now,
    lanes: [
      {
        id: "22222222-2222-4222-8222-222222222222",
        slug: "security-sanitize",
        branch: "orch/security-sanitize",
        status: "active",
        anchorSha: "abcdef0123456789",
        shortSha: "abcdef0",
        prUrl: null,
        modelHint: "cursor-sonnet",
        lastSyncAt: now,
        commitsAhead: 3,
        dirty: false,
        lastCommitMessage: "Sanitize auth helpers",
        hasUpstream: true,
        unpushedCommits: 0,
        plainStatus: "3 commits ahead of main",
        nextStep: "Open a pull request from this desk when you’re ready.",
      },
      {
        id: "33333333-3333-4333-8333-333333333333",
        slug: "billing-fix",
        branch: "orch/billing-fix",
        status: "pr_open",
        anchorSha: "fedcba9876543210",
        shortSha: "fedcba9",
        prUrl: "https://github.com/example/repo/pull/9",
        modelHint: null,
        lastSyncAt: now,
        commitsAhead: 5,
        dirty: false,
        lastCommitMessage: "Fix invoice rounding",
        hasUpstream: true,
        unpushedCommits: 0,
        plainStatus: "Pull request open",
        nextStep: "Review the pull request, or keep working in the folder.",
      },
      {
        id: "44444444-4444-4444-8444-444444444444",
        slug: "legacy-cleanup",
        branch: "orch/legacy-cleanup",
        status: "merged",
        anchorSha: "0123456789abcdef",
        shortSha: "0123456",
        prUrl: null,
        modelHint: null,
        lastSyncAt: now,
        commitsAhead: 0,
        dirty: false,
        lastCommitMessage: "Remove dead flags",
        hasUpstream: true,
        unpushedCommits: 0,
        plainStatus: "Merged",
        nextStep: "Nothing left — you can remove this worker.",
      },
      {
        id: "55555555-5555-4555-8555-555555555555",
        slug: "stale-docs",
        branch: "orch/stale-docs",
        status: "orphaned",
        anchorSha: "deadbeefcafebabe",
        shortSha: "deadbee",
        prUrl: null,
        modelHint: null,
        lastSyncAt: null,
        commitsAhead: 0,
        dirty: false,
        lastCommitMessage: null,
        hasUpstream: false,
        unpushedCommits: 0,
        plainStatus: "Folder missing",
        nextStep: "Start this worker again, or remove it.",
      },
      {
        id: "66666666-6666-4666-8666-666666666666",
        slug: "parked-experiment",
        branch: "orch/parked-experiment",
        status: "stashed",
        anchorSha: "cafebabedeadbeef",
        shortSha: "cafebab",
        prUrl: null,
        modelHint: null,
        lastSyncAt: now,
        commitsAhead: 1,
        dirty: true,
        lastCommitMessage: "WIP experiment",
        hasUpstream: false,
        unpushedCommits: 0,
        plainStatus: "Unfinished local edits",
        nextStep: "In the worker chat: commit (and push). Then refresh here.",
      },
    ],
  };
  return TrunkScanSnapshotSchema.parse({ ...base, ...overrides });
}

export function fixtureSyncLog(overrides?: Partial<SyncLog>): SyncLog {
  const base: SyncLog = {
    schema: "orchestra.sync_log.v1",
    planId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    workerSlug: "security-sanitize",
    repoSlug: "fixture-repo",
    branch: "orch/security-sanitize",
    status: "progress",
    summary: "Sanitized auth helpers; awaiting review on edge cases.",
    commits: ["abcdef0"],
    filesTouched: ["src/lib/auth/index.ts"],
    blockers: [],
    nextAction: "Open PR when fence checks pass",
    recordedAt: new Date().toISOString(),
  };
  return SyncLogSchema.parse({ ...base, ...overrides });
}
